### ISSUE TITLE
Can't Navigate to Multiple Groups in Same Location 

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#112]
(See oakland CA on map)

**Comment by ejucovy** [comment]
Oh wow yeah I hadn't noticed that.  Seems to be a fundamental problem with the underlying JS library markerclusterer that we are using.

But I cobbled together a solution that does the following:

1) When adding a new Google Marker to the map, check if there's another marker already on the map with an identical lat/lng.

2) If so, instead of adding a new marker, append the new object's info to the existing marker, separated with an `<hr/>`

3) And also, replace the default (Red Point) marker with the same (Green House) marker that's used to represent clustered markers.

There are a few drawbacks though:

1) I haven't yet figured out how to display a number in the house, so it's just a green house without any number on it when it's not clustered with other objects.  Strictly speaking this would be an enhancement, because the existing implementation just displays a single red marker when zoomed in fully.

2) Since it's internally stored as a single marker with multiple pieces of info on it, the markerclusterer library doesn't know about it -- so if a group of six objects in the exact same location is clustered with another two objects, the clustered icon displays "3" instead of "8" -- this is strictly speaking a regression, because the existing implementation does correctly display the total number of groups when zoomed out far enough.

I think this is probably good enough to move forward with for now, though.

Another thing to consider would be using a different marker here rather than reusing the "Green House" icon.

**Comment by ejucovy** [comment]
Implemented for all three maps in 7351053

**Comment by jwarnow** [comment]
We definitely want to replace the green house (there and everywhere) -- especially if that helps with general clustering behavior.

**Comment by ejucovy** [comment]
The change is now deployed -- you can test it out by looking at groups in Oakland, or users on Long Island.

Let's file new tickets for swapping the icons, and for the two problems I mentioned -- this one's OK to re-close, right?  Is this current behavior an improvement over the previous behavior at least?

**Comment by jwarnow** [comment]
Yep, let's close this out.
