### ISSUE TITLE
Add text for empty tabs

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#114]
Right now, several of the tabs on events and users present just a blank space when there is no content to populate it. We should probably replace it with explanatory text:

EMPTY GROUP TABS

*Events
*Campaigns

EMPTY USER TABS

*Overview
*Projects
*Groups
*Campaigns

**Comment by ejucovy** [comment]
Group>Events: 0bd56db5c and 58eb075

**Comment by ejucovy** [comment]
Group>Campaigns: 0387483

**Comment by ejucovy** [comment]
Group>Projects: 4d6f247

**Comment by ejucovy** [comment]
I implemented the empty-tab texts for user profile overview, projects and groups in 0b9f3a3cf4b7537f412497381a0fff64fa94eed4 and 3d6dbd6aeeae025971ea44d949874c3a6c5ac7fd

**Comment by ejucovy** [comment]
I just discovered that campaigns are actually not wired up at all in the user profile template -- the "Campaigns" tab is empty and doesn't load any dynamic data, and likewise the "Campaigns Completed" counter on the sidebar is hardcoded to display zero.

I filed a separate (high priority) ticket #122 to track this, and I'll add the campaign empty-tab text conditions in when I implement that.  So, closing this ticket since every other piece is done.
