### ISSUE TITLE
Adding external groups: sidestep account creation

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#115]
The external group feature was envisioned as a super streamlined, lightweight option for the people who have a group already and groan at the idea of having to join "yet another" thing. As such, it would be ideal if people could add their external groups to the map without creating an account. Thoughts?

**Comment by ejucovy** [comment]
This should be fine.  A few considerations:

1) We'll definitely need to make sure that there is a mechanism for emails to be sent to site administrators notifying them of new groups being created, so that there is an opportunity to catch spam.  After all, this feature would specifically allow anonymous users to post links from the groups.350.org site so you'd need, at minimum, some human moderation in place to keep the content relevant.

2) Groups created in this way would have no administrator, so no one would be able to upgrade the external group to a fully-featured group on the site (or edit it, or delete it) -- if a user wanted these capabilities he would have to get in touch with a site admin (e.g. via email) who would decide whether or not to manually make the user's account an owner of the group.  This is all fairly straightforward through the admin interface, but note that it would have to involve informal communications and trust/judgement calls outside the scope of the system itself.

**Comment by jwarnow** [comment]
Great stuff -- both #1 & #2 make sense. So long as we can upgrade these
manually later on, we should be good to go...

-jw-

**Comment by ejucovy** [comment]
Implemented in b2587c6 -- but I'd better add the admin-email-notification thing ASAP now.
