### ISSUE TITLE
Eliminate unnecessary Facebook App Requests

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#124]
A couple that are red flags to me when I'm considering logging in with FB:
- Post to Facebook as me
  350groups-dev may post status messages, notes, photos, and videos on my behalf
- Access my data any time
  350groups-dev may access my data when I'm not using the application

Do we really need those? I think we just want the ability to send/access email address and access basic info is what the priority should be...

**Comment by ejucovy** [comment]
I don't think we need "Access my data any time" (as far as I know)

"Post to Facebook as me" is used, though, for auto-sharing of completed projects/actions.  On our end we actually ask the user whether he wants to enable this feature, so it's a bit annoying that we have to have it in the Facebook OAuth permission form -- which I agree makes it sound sorta creepy.

Any suggestions on how to approach this?  I suppose we could disable the facebook auto-sharing feature, though it'd be a shame to lose that feature just because of the rigidity of OAuth permissioning/UI.  (I am not a fan of OAuth, in case you can't tell!)

**Comment by jwarnow** [comment]
I think it's OK to disable FB auto-sharing. I don't think that's going to be
a significant driver of traffic and recruitment, even if it was turned on...

**Comment by ejucovy** [comment]
Okay, will do.

**Comment by ejucovy** [comment]
Narrowed down the permission requests to the bare minimum in 60124bd00957dc3ef2556121ea415b4d0b4f8654

Removed the "Ask To Share on Social Networks" modal dialog, after acting on a solo task, in dd2e10c4f035688011d7c2cc2b99906ae037132f
