### ISSUE TITLE
First Import List for External Groups

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#126]
Here's a good batch: https://docs.google.com/a/350.org/spreadsheet/ccc?key=0AqkvFIPJuevMdFhCQWNZWWJGUVN1X0JiSVlaX1R4NUE&hl=en_US#gid=1

**Comment by ejucovy** [comment]
There are two sheets on that spreadsheet, should I only import data from Sheet 2?

**Comment by jwarnow** [comment]
Yep, just sheet 2

**Comment by ejucovy** [comment]
The "350 Tonga" group has no URL listed.  I wasn't able to find one with a Google search either ("350 Tonga" returned a bunch of realtor listings and currency conversions...) -- do you have a URL for it?

If not I'll have to leave that one out, because "external only" groups will break if they don't have a link, and non-external groups will break if they don't have any members.

**Comment by jwarnow** [comment]
Yea, just leave that one out...

**Comment by ejucovy** [comment]
OK, I've imported everything else.
