### ISSUE TITLE
Enable "contact the group leader" webform, before users join group

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#127]
Many folks want an initial email contact before joining -- this should be enabled. Also, would enable different groups to coordinate and message eachother.

**Comment by abea** [comment]
As an update, we'd like to have “contact the group” be an option, without email address being public, on the map pop-ups and the group landing page before sign-up.

**Comment by jwarnow** [comment]
Just to clarify: the message should still just go to the group leader, not
to the whole group.

**Comment by ejucovy** [comment]
Implementation done in a58f89bc85fdceef9199dd6d178a4b02a4fbb79a and d88db22df5ea037906279ec7db7853de9a52427e and initial link put in place in f9542fc

**Comment by ejucovy** [comment]
Some of the pre-existing external groups will have no group leaders on file.  Rather than having those groups be un-contact-able, I've added some logic to send the message to the site email address (`messages at 350 dot org`) if there are no "real" managers.  I added that in 0d1056137ddfebad6d3642ac06336ef291e37d5d

**Comment by ejucovy** [comment]
Added a "contact group leaders" link on the "group list" map popup bubbles in ab9de57effba8989971eaf11850bf641aaf05af6

**Comment by ejucovy** [comment]
"Contact event organizers": ee91188

**Comment by ejucovy** [comment]
"Contact petition/campaign organizers": 193c17f5395ae818235054b7c86a1bb9efa6d633
