### ISSUE TITLE
ActionKit tags

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#132]
we'll want to tag everyone who gets pushed to AK with "350groups" and group leaders as "hosts" so we can more easily communicate with them through AK

**Comment by ejucovy** [comment]
When you say "tag" do you mean a custom ActionKit user field?  If so, the documentation says this:

"In ActionKit, you can create custom user fields to store additional information with each User record. You can update and retrieve these user fields using the API. In order to append a field to a User record you first have to add it as an allowed user field.  See 'Edit Custom User Fields' in the ActionKit Admin."

Could you add a couple of allowed custom user fields for this, if that's what you mean?

It might also be good to add some additional fields like "350groups_username" and "350groups_contributor_signed_up_by" (or something along those lines) to additionally track people -- on this note, I'll email you with some thoughts about ActionKit stuff that I've been queuing up.

**Comment by jwarnow** [comment]
I was actually hoping to use ActionKit tags, at least for the basic
categorization (like group-member or group-leader) so that we can easily
target them using the Email Blast targetter. Using custom AK user fields for
the other things (GroupURL?) might make good sense.

Technically, tags are associated with pages, and users inherit them by using
those pages directly or by  using the API to associate the users with those
pages.

More here:
https://roboticdogs.actionkit.com/docs/manual/guide/page.html#tags

**Comment by ejucovy** [comment]
Group managers now get signed up on a second page in addition to the one that everybody gets signed up on.  If a user becomes a group manager later on, he'll get signed up on that second page when he becomes a manager.  At the moment users remain on that second page even after they've been demoted from group management.
