### ISSUE TITLE
Zoom out groups map

### ISSUE THREAD

**Issue by abea** [350dotorg/localpower#158]
We'd like the Find a group map at http://local.350.org/groups/ to be a full world view rather than just the US.

**Comment by abea** [comment]
Can I get an update on this and the other issues--especially the error with my and the DC350 group pages showing the error screen?

**Comment by ejucovy** [comment]
Done, and also done for the User Map and Event Map.  But, two things to note:
1. If the map is viewed by a logged-in user whose location is filled in, the map is centered on the user's listed location.  The "US map" is just the default for non-logged-in users or users with no known location.  I think it makes sense to keep this behavior, so that by default logged-in users see a map of groups in their region.
2. As you'll see, a whole-world map is a little awkward, because the dimensions of the world map don't fit the dimensions of the map pane well -- so there's some wrapping and duplication (e.g. Asia appearing on both sides of the map) that's a little strange.

**Comment by ejucovy** [comment]
> the error with my and the DC350 group pages showing the error screen?

This should now be fixed; see https://github.com/350org/localpower/issues/166
