### ISSUE TITLE
Change link to start groups

### ISSUE THREAD

**Issue by abea** [350dotorg/localpower#163]
Please change the link for the "Start a group" button at local.350.org/groups to go to http://local.350.org/groups/new/.

**Comment by ejucovy** [comment]
It actually does go to http://local.350.org/groups/new/ unless the user is a site admin//staff member.  I wanted to leave the "real" form available for 350 staff to fill in once they've verified group creation requests, so I set up the page at http://local.350.org/groups/create/ to force-redirect the user to http://local.350.org/groups/new/ unless he's a staff member.

If you log out of your admin account and click the "Start a group" button you'll see the expected behavior.

**Comment by abea** [comment]
I see. Thanks, Ethan. This can be closed.

Alex Bea
(202) 525-6703 | http://350.org

On Sun, Jan 8, 2012 at 2:57 PM, ejucovy <
reply@reply.github.com
