### ISSUE TITLE
Group page failing when user is made manager

### ISSUE THREAD

**Issue by abea** [350dotorg/localpower#170]
This might be another specific to stuff I've done with my users. Both the users I have for alex@350.org and alex.bea@gmail.com are seeing an internal server error page when going to the DC test group now that I made them group managers.

Alex

**Comment by ejucovy** [comment]
The problem was that a "group association request" persisted in the system after its associated Event was deleted, causing the system to crash when it accessed that "group association request".  I added code to clear these out when Events (and Campaigns and Actions) are deleted: aaf993d9aa0033a1861992f5a143c2513de0bcb9
