### ISSUE TITLE
Facebook connect prompt post project completion needs modal

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#20]
The CSS for the modal that pops up after a project is completed is not there.

**Comment by ejucovy** [comment]
Adding the CSS and images for a jquery.ui theme in 991b2725 + 8980138 seems to have fixed this.  The popup is now looking nice.

But, there's a broken image link in the popup: /images/theme/we_fb.jpg

**Comment by ejucovy** [comment]
I filed #56 about the broken image; I'll close this ticket now.

For future reference, since it took me a while to trace through: the Facebook Connect Prompt is the "Ask To Share" widget in the `records` app.  It's invoked in the `base/base.html` template depending on a context variable that's injected via the `records.context_processors.ask_to_share` template context processor, conditional on a token's presence in the request session.  (If it is present, the same context processor also removes it from the session, so that the prompt doesn't recur.)  That token is put into the session, conditional on some user profile settings, in the `records.models.publish_to_social_networks` function that's connected to the `records.signals.record_created` signal.  That signal is fired after a successful user action in `actions.views` code (`action_complete` and `action_commit`) depending on the prior state of the completion/commitment, as determined in `actions.models.complete_for_user` and `actions_models.commit_for_user` -- specifically, the Ask To Share prompt only appears if the commitment/completion is new, rather than an update of an earlier commitment/completion.  Whew!  (I should really put this in the wiki or code-documentation somewhere, but for now I'll just stash it here.)  Anyway, the upshot is that firing a `record_created` signal is the way to cause the Ask To Share prompt to appear on the next request.
