### ISSUE TITLE
Flash messages need to be integrated into the page design

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#24]
Flash messages are the things that show up at the top of the page with a warning, information, or a confirmation. They are built in and being generated, but they are not output in the templates. 

They need to be designed and then coded in.

**Comment by ejucovy** [comment]
I see that there's already a `_messages.html` template -- and its inclusion is present, but commented out, just inside the main 12-column div in `base/base.html`

I'm reactivating that inclusion, in 777cd00 -- it needs styling badly, but I'd rather have it present and ugly than not at all for now, since it'll help us catch missing or incorrect messages (e.g. see #57, #58)

**Comment by ejucovy** [comment]
I integrated them better into the templates, added some CSS that looks at least halfway decent, and wrapped them in the necessary HTML for the `base.js` Javascript hooks, in the following commits:
- 18c101068
- c09f0d40d
- 23ecd850767c
- 4bb1e0eba1
