### ISSUE TITLE
fix calendar on event create page

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#38]
Calendar for picking the day of the event is broken. There is some missing CSS for the jQuery UI widgets.

**Comment by ejucovy** [comment]
I added the themeroller "lightness" theme in 991b272 and 8980138 which made the calendar look nice.

There was still a problem where two calendar widgets were showing up -- one when the page loaded, present always, and a second, overlaid on top of the first with a slight offset, when the "when" formfield gained focus.  This was because the pages/base.js JS runs `$(".datepicker").datepicker()` and the base/_form.html causes the "datepicker" class to be rendered twice -- once on the form_row div, and again on the formfield itself.  I fixed this in 58bf0b9d but I don't know if that will have consequences elsewhere -- perhaps instead the pages/base.js should run something like `$("input.datepicker").datepicker()` (actually I like that more -- will probably revert)

Also adding the jquery-ui CSS/images magically made some tabs work, and look nice, on the profile-edit form!

**Comment by ejucovy** [comment]
> Also adding the jquery-ui CSS/images magically made some tabs work, and look nice, on the profile-edit form!

I see this also made some popups/overlays magically work and look nice, e.g. the "Facebook Connect" prompt that occurs after committing to an action.

**Comment by ejucovy** [comment]
In f5b83631a4631d754e2796bebe5504938afa4d96 I reverted the change I made to the base form template's markup, and instead made the `pages/base.js` only invoke `$.datepicker()` on `input.datepicker` rather than `.datepicker` -- which is more correct (datepicker isn't meant to work on non-input elements) and has less potential to impact other code than my previous fix.
