### ISSUE TITLE
Event invites should have their own form page

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#39]
After you create an event, there is an option to invite people. This should link to a new page with the invite form.

**Comment by ejucovy** [comment]
See also #40, #41, #42

**Comment by ejucovy** [comment]
Fixed in 4a3686c

**Comment by ejucovy** [comment]
I'm rendering the form fields, but not actually wrapping them in a <form> -- that's handled outside of _form.html -- need to fix this.

**Comment by ejucovy** [comment]
Urgh, never mind, that's not correct -- they are wrapped in a form tag, but it's not picking up the CSS styles because they're only hung on `form.form_6c` objects.  I'm re-closing all these tickets and I'll file a single separate issue to style all these forms -- since they can/should all be done with a single approach.
