### ISSUE TITLE
Event "add a guest" should have it's own form page.

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#40]
Link is in the Host Tools on the event detail page. Visible to event hosts.

**Comment by ejucovy** [comment]
See also #41 and #42 (similar event-form-template related issues)

**Comment by ejucovy** [comment]
Fixed in 0668ab8 (though this, like the other event-related forms, could use some nicer CSS -- but, one thing at a time)

**Comment by ejucovy** [comment]
I'm rendering the form fields, but not actually wrapping them in a <form> -- that's handled outside of _form.html -- need to fix this.  Will probably fix the design issues I'm seeing.

**Comment by ejucovy** [comment]
Urgh, never mind, that's not correct -- they are wrapped in a form tag, but it's not picking up the CSS styles because they're only hung on `form.form_6c` objects.  I'm re-closing all these tickets and I'll file a single separate issue to style all these forms -- since they can/should all be done with a single approach.
