### ISSUE TITLE
Event "select hosts" should have it's own form page.

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#41]
Linked from the Host Tools module on event detail pages.

**Comment by ejucovy** [comment]
In 16e6745 I gave the events/hosts.html and events/_hosts.html templates the same treatment as the main events form templates (per #42) -- so it now renders something.

Also in d58a0ccf7faa9297526d9c4c4a619583f17f3d95 I gave the HostForm the somewhat less confusing label "Hosts" instead of "Guests"

**Comment by ejucovy** [comment]
I'm rendering the form fields, but not actually wrapping them in a `<form>` -- that's handled outside of _form.html -- need to fix this.  Will probably fix the design issues I'm seeing.

**Comment by ejucovy** [comment]
Urgh, never mind, that's not correct -- they are wrapped in a form tag, but it's not picking up the CSS styles because they're only hung on `form.form_6c` objects.  I'm re-closing all these tickets and I'll file a single separate issue to style all these forms -- since they can/should all be done with a single approach.
