### ISSUE TITLE
Event editing should use the form template

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#42]
Editing an event should use the full page form template.

**Comment by ejucovy** [comment]
Fixed in 76c7579 -- now extends base/form.html -- also, it was including a blank events/_form.html template which I changed to the standard base/_form.html template.

**Comment by ejucovy** [comment]
I'm rendering the form fields, but not actually wrapping them in a `<form>` -- that's handled outside of _form.html -- need to fix this.  Will probably fix the design issues I'm seeing.

**Comment by ejucovy** [comment]
Urgh, never mind, that's not correct -- they are wrapped in a form tag, but it's not picking up the CSS styles because they're only hung on `form.form_6c` objects.  I'm re-closing all these tickets and I'll file a single separate issue to style all these forms -- since they can/should all be done with a single approach.
