### ISSUE TITLE
Remove "Create an Account" section of the logged out home page carousel

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#52]
The last pane of the logged out home page carousel should just be removed.

**Comment by ejucovy** [comment]
0e30282 relates to this (removing the 1st panel's mega-button link to the 4th panel)

Rather than removing the fourth panel altogether, it might be preferable to replace it with another content panel, maybe about challenges/campaigns or events.  We'd need an extra image for that of course (though I think Jon W. has indicated 350.org will want to replace most of the stock-photo-style images so this might not be much extra work?)

**Comment by jonlesser** [comment]
I believe (hope) I wrote the JS such that it will work with any number of
panels. So deleting the last panel, which has an image of a form, doesn't
need to be dependent on new panel content.

**Comment by ejucovy** [comment]
In 1030b5f I replaced the fourth panel with some kinda generic text about events.  I thought this would be preferable to removing it altogether; somehow with only three panels it just feels ... rhetorically unbalanced.
