### ISSUE TITLE
SSL Error when accessing certain pages. 

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#83]
See:  http://i.imgur.com/Pcsqo.jpg

How to fix?

**Comment by ejucovy** [comment]
The site forces certain URLs to be accessed over HTTPS instead of HTTP -- specifically, the entire admin site, and any page that could potentially involve the user sending his password over the wire (so, account registration, login, etc)

We'll have to install a trusted SSL certificate on the server(s) in order for this go to away.  Does 350.org have an existing SSL wildcard certificate (valid for *.350.org) that we can install?  Otherwise we'll have to (you'll have to) get one from a trusted SSL certificate authority.  (This costs a bit of money per year, sort of like registering a domain name.)  Let's follow up on this one via direct email.

Alternatively, we could disable SSL entirely and serve the entire site over HTTP at the expense of the added security that HTTPS offers.

(For the record, you can safely ignore the error and "proceed anyway" to access the functionality.)

**Comment by ejucovy** [comment]
We can revisit this if/when we decide to reenable SSL.
