### ISSUE TITLE
HTML Editor Doesn't Load From WYSIWYG

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#88]
Clicking HTML icon in TinyMCE toolbar launches window that doesn't load.

**Comment by ejucovy** [comment]
Googling for this turns up http://stackoverflow.com/questions/572025/tiny-mce-popups-blank-in-django-admin -- so, it seems to be a result of our hosting static media on a separate (S3) domain.  It sounds like there's no workaround short of moving the media back to a 350.org domain.

It seems that it's possible to point a custom subdomain to an S3 bucket: http://stackoverflow.com/questions/5043616/amazon-s3-static-web-sites-custom-domain-or-subdomain

I'll follow up about this over email shortly.

**Comment by ejucovy** [comment]
After setting up the S3 buckets' DNS we'll then need to follow the steps listed in http://www.tinymce.com/wiki.php/How-to_load_TinyMCE_crossdomain I think.

**Comment by ejucovy** [comment]
I've set up three S3 buckets conforming to the necessary naming conventions, and enabled their "Website" feature with the AWS console.  I copied the contents of the old buckets to these new ones, made sure everything is public, and set up disambiguating index.html pages for each.  Next step is to set up some DNS CNAME records to activate the real subdomains.

**Comment by jwarnow** [comment]
Let me know if you need me to make DNS tweaks, and what they should be.

**Comment by ejucovy** [comment]
I've updated the various local_settings and nginx config files to use the new 350.org subdomains for static media.

**Comment by ejucovy** [comment]
Phew, finally got this right, running against staging.static.groups.350.org

The problem is now solved (though you may need to manually visit http://staging.static.groups.350.org/js/tiny_mce/tiny_mce.js and http://staging.static.groups.350.org/js/tiny_mce/tiny_mce_popup.js in your browser and shift+reload them, in order to make sure no cached copies are getting in the way of it) and the HTML popup button works properly.
